package org.dse.mobile.core.api

object ExistingErpRoutes {
    const val HEALTH="/api/auth/health"
    const val RUNTIME_HEALTH="/api/runtime/health"
    const val PROFILE="/api/profile"
    const val CHANGE_PASSWORD="/api/auth/password"
    const val LOGIN="/api/auth/login"
    const val MFA_COMPLETE="/api/auth/login/mfa/complete"
    const val MFA_RESEND="/api/auth/login/mfa/resend"
    const val PASSWORD_RESET_REQUEST="/api/auth/password-reset/request"
    const val PASSWORD_RESET_COMPLETE="/api/auth/password-reset/complete"
    const val REGISTRATION_CAPTCHA="/api/auth/registration/captcha"
    const val REGISTRATION_REQUEST="/api/auth/registration/request"
    const val REGISTRATION_EMAIL_VERIFY="/api/auth/registration/email/verify"
    const val REGISTRATION_MFA_COMPLETE="/api/auth/registration/mfa/complete"
    const val REGISTER="/api/auth/register"
    const val REGISTRATION_ROLES="/api/auth/registration-roles"
    const val LOGOUT="/api/auth/logout"
    const val SESSION_EXTEND="/api/auth/session/extend"
    const val EFFECTIVE_PERMISSIONS="/api/auth/effective-permissions"

    const val SALES_PAGE="/api/operations/sales/page"
    const val SALE_BY_INVOICE="/api/operations/sales/by-invoice"
    const val SALES="/api/operations/sales"
    const val SALES_CANCEL="/api/operations/sales/cancel"
    const val SALES_APPROVE="/api/operations/sales/approve"
    const val SALES_REJECT="/api/operations/sales/reject"
    const val SALES_NEXT="/api/operations/sales/next-invoice"

    const val PURCHASES_PAGE="/api/operations/purchases/page"
    const val PURCHASE_BY_INVOICE="/api/operations/purchases/by-invoice"
    const val PURCHASES="/api/operations/purchases"
    const val PURCHASES_CANCEL="/api/operations/purchases/cancel"
    const val PURCHASES_APPROVE="/api/operations/purchases/approve"
    const val PURCHASES_REJECT="/api/operations/purchases/reject"
    const val PURCHASES_NEXT="/api/operations/purchases/next-invoice"

    const val FINANCE_PAGE="/api/operations/finance/page"
    const val FINANCE="/api/operations/finance"
    const val FINANCE_METRICS="/api/operations/finance/metrics"
    const val FINANCE_NEXT="/api/operations/finance/next-voucher"
    const val STOCK_HISTORY="/api/operations/stock/history"
    const val STOCK_ADJUST="/api/operations/stock/adjust"

    const val QUOTATIONS="/api/quotations"
    const val QUOTATIONS_PAGE="/api/quotations/page"
    const val QUOTATION_SOURCES="/api/quotations/sources"

    const val RETURNS="/api/returns"
    const val RETURNS_PAGE="/api/returns/page"

    const val BANK_STATEMENTS="/api/bank-statements"
    const val PURCHASE_RECON="/api/purchase-recon"

    const val PARTIES="/api/master/parties"
    const val PARTIES_SEARCH="/api/master/parties/search"
    const val PARTIES_NEXT="/api/master/parties/next-code"
    const val ITEMS="/api/master/items"
    const val ITEMS_SEARCH="/api/master/items/search"
    const val ITEMS_NEXT="/api/master/items/next-code"
    const val SALES_ENTRY_BOOTSTRAP="/api/master/sales-entry-bootstrap"
    const val LOOKUPS="/api/master/lookups"
    const val LOOKUP_VALUES_BY_CODE="/api/master/lookups/values-by-category-code"
    const val LOOKUPS_BY_CODE="/api/master/lookups/by-category-code"
    const val LOOKUPS_NEXT="/api/master/lookups/next-code"
    const val CATEGORIES="/api/master/categories"
    const val CATEGORIES_UPSERT="/api/master/categories/upsert"
    const val REFERENCE_FORMATS="/api/master/reference-formats"

    const val SUPPORT="/api/support"
    const val SETTINGS="$SUPPORT/settings"
    const val AUDIT="/api/audit"
    const val CUSTOMER_360="/api/customer-360"
    const val SUPPLIER_360="/api/supplier-360"
    const val STORAGE="/api/storage"
    const val SETUP="/api/setup"
    const val UPDATES="/api/updates"
    const val SERVER_RESOURCES="/api/authority/resources"
    const val PAYMENTS="$SUPPORT/payments"
    const val PAYMENTS_WITH_ID="$SUPPORT/payments/with-id"
    const val GLOBAL_SEARCH="$SUPPORT/search"
    const val RESOLVE_RECORD="$SUPPORT/resolve-record"
    const val SAVED_VIEWS="$SUPPORT/saved-views"
    const val COMMUNICATIONS="$SUPPORT/communications"
    const val ACTIVITY="$SUPPORT/activity"
    const val BUSINESS_EMAIL="/api/authority/email"
    const val BUSINESS_EMAIL_RESEND="$BUSINESS_EMAIL/resend"
    const val BUSINESS_EMAIL_SETTINGS="$BUSINESS_EMAIL/settings"
    const val BUSINESS_EMAIL_TEST="$BUSINESS_EMAIL/test"
    const val CANONICAL_DOCUMENT="/api/documents/render"

    const val INSIGHTS="/api/insights"
    const val INSIGHTS_DASHBOARD="$INSIGHTS/dashboard"
    const val REMINDERS="$INSIGHTS/reminders"
    const val NOTIFICATIONS="$INSIGHTS/notifications"
    const val NOTIFICATION_PREFERENCES="$INSIGHTS/notification-preferences"
    const val SHELL_COUNTS="$INSIGHTS/shell-counts"
    const val REPORTS="$INSIGHTS/reports"
    const val REPORT_FILTERS="$INSIGHTS/reports/filters"

    const val ADMIN="/api/admin"
    const val ADMIN_USERS="$ADMIN/users"
    const val ADMIN_ROLES="$ADMIN/roles"
    const val ADMIN_PERMISSIONS="$ADMIN/permissions"
    const val ADMIN_PERMISSION_SET="$ADMIN/permissions/set"
    const val ADMIN_REGISTRATION_ROLE="$ADMIN/registration-role"
    const val ADMIN_REGISTRATIONS="$ADMIN/registrations"
}

object MobileV1Routes {
    const val BASE="/api/mobile/v1"
    const val DASHBOARD="$BASE/dashboard"
    const val SYNC="$BASE/sync"
    const val SHIPPING="$BASE/shipping"
    const val SHIPPING_BY_ID="$BASE/shipping/{id}"
}
