package org.dse.mobile.core.model

import kotlinx.serialization.Serializable

@Serializable data class UnifiedReportDefinition(val id:String="",val category:String="",val title:String="",val description:String="",val groupByOptions:List<String> = emptyList(),val supportedFilters:List<String> = emptyList())
@Serializable data class UnifiedReportFilters(val parties:List<String> = emptyList(),val customers:List<String> = emptyList(),val suppliers:List<String> = emptyList(),val items:List<String> = emptyList(),val salespeople:List<String> = emptyList(),val documentStatuses:List<String> = emptyList(),val paymentStatuses:List<String> = emptyList(),val returnStatuses:List<String> = emptyList(),val gstRates:List<String> = emptyList(),val warehouses:List<String> = emptyList(),val bankStatuses:List<String> = emptyList())
@Serializable data class UnifiedReportRequest(val reportId:String="",val from:String="",val to:String="",val party:String="",val item:String="",val salesperson:String="",val documentStatus:String="",val paymentStatus:String="",val returnStatus:String="",val gstRate:String="",val warehouse:String="",val bankStatus:String="",val search:String="",val groupBy:String="",val sortKey:String="",val sortDirection:String="",val minAmount:Double?=null,val maxAmount:Double?=null,val page:Int=0,val size:Int=50,val visibleColumns:List<String> = emptyList())
@Serializable data class UnifiedReportColumn(val key:String="",val label:String="",val type:String="",val defaultVisible:Boolean=true,val numeric:Boolean=false,val preferredWidth:Double=0.0)
@Serializable data class UnifiedReportMetric(val key:String="",val label:String="",val value:Double=0.0,val format:String="",val note:String="")
@Serializable data class UnifiedReportRow(val rowKey:String="",val values:List<String> = emptyList(),val groupKey:String="",val targetFxml:String="",val targetId:Long?=null,val referenceNo:String="")
@Serializable data class UnifiedReportResult(val reportId:String="",val title:String="",val description:String="",val periodFrom:String="",val periodTo:String="",val metrics:List<UnifiedReportMetric> = emptyList(),val columns:List<UnifiedReportColumn> = emptyList(),val rows:List<UnifiedReportRow> = emptyList(),val totalRows:Long=0,val page:Int=0,val size:Int=50,val totalPages:Int=0,val groupByOptions:List<String> = emptyList(),val appliedFilters:Map<String,String> = emptyMap(),val totals:Map<String,String> = emptyMap(),val generatedAt:String="",val generatedBy:String="")
@Serializable data class ReportScheduleRow(val id:Long=0,val name:String="",val savedReport:String="",val reportTitle:String="",val datePreset:String="",val frequency:String="",val dayOfWeek:Int?=null,val dayOfMonth:Int?=null,val monthOfYear:Int?=null,val time:String="",val format:String="",val delivery:String="",val recipients:String="",val nextRun:String="",val lastRun:String="",val status:String="",val lastStatus:String="",val lastError:String="",val rowVersion:Long=0)
@Serializable data class ReportScheduleRequest(val name:String="",val savedReport:String="",val frequency:String="",val dayOfWeek:Int?=null,val dayOfMonth:Int?=null,val monthOfYear:Int?=null,val time:String="",val format:String="",val delivery:String="",val recipients:String="",val rowVersion:Long=0)
@Serializable data class ReportScheduleSummary(val activeSchedules:Long=0,val nextRun:String="",val nextSchedule:String="",val reportsThisMonth:Long=0,val failuresLast30Days:Long=0)
@Serializable data class SavedReportOption(val name:String="",val reportId:String="",val title:String="",val datePreset:String="")
@Serializable data class ReportRunHistory(val id:Long=0,val scheduleId:Long=0,val startedAt:String="",val finishedAt:String="",val status:String="",val reportTitle:String="",val format:String="",val delivery:String="",val rowCount:Long=0,val artifacts:String="",val error:String="",val triggeredBy:String="")
@Serializable data class ReportSchedulePage(val schedules:List<ReportScheduleRow> = emptyList(),val summary:ReportScheduleSummary=ReportScheduleSummary())
@Serializable data class ReportScheduleResult(val success:Boolean=false,val message:String="")
